# 1. Creation of NumpyArrays

### Creating Array

In [11]:
import numpy as np
x = np.array([5, 8, 
              9, 10, 
              11]) # using 'array' method

type(x)   # Displays type of array 'x'
print(x)

[ 5  8  9 10 11]


In [32]:
y = np.array([[6, 9, 5], 
              [10, 82, 34]])  
print(y)

[[ 6  9  5]
 [10 82 34]]


### Array Attributes

In [33]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)

2 (2, 3) 6 int32 4 24


In [15]:
z = np.array([3+4j, 0.4+7.8j])
print(z.dtype)

complex128


In [16]:
x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

8


### Multi Dimensional Array

In [30]:
n = [[-1, -2, -3, -4], [-2,-4, -6, -8]]
x = np.array(n)
print(type(x))
print(x.ndim, x.shape, x.size, x.itemsize, x.dtype)

<class 'numpy.ndarray'>
2 (2, 4) 8 4 int32


In [32]:
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 
     [[8.6, 9.9], [3.6, 4.3], [6.6, 0.3]],
     [[8.6, 9.9], [3.6, 4.3], [6.6, 0.3]]]

x = np.array(a, dtype='float64')

type(x), x.ndim, x.shape

(numpy.ndarray, 3, (3, 3, 2))

### Array Creation Methods 
#### ones, zeros, full, eye

In [39]:
x = np.zeros(shape=(2,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
y = np.full(shape=(2,3), fill_value=10.5)
print(y)
y1 = np.full(shape=(3,4,2), fill_value=np.random.rand(2))
print(y1)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]
[[[0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]]

 [[0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]]

 [[0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]
  [0.52275371 0.23409532]]]


In [34]:
z = np.eye(4,4)  #gives 1 diagonally
print(z)
print(z.shape, z.ndim)
z1 = np.eye(3,4,2)
print(z1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4) 2
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [24]:
x1 = np.ones(shape=(4,2))
print(x1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Numeric Sequence Generators
#### arange & linspace

In [37]:
# arange : Syntax - numpy.arange([start, ]stop, [step, ]dtype=None)
y = np.arange(3, 15, 2.5) # 2.5 step between
print(y)

#Define a ndarray x6, having first 20 even numbers.
y1 = np.arange(2, 41, 2) 
print(y1)

[ 3.   5.5  8.  10.5 13. ]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [38]:
# linspace : Syntax - numpy.linspace(start, stop, #num inbetween, endpoint=True, retstep=False, dtype=None)
y = np.linspace(3, 15, 4) # 5 is size of array 'y'
print(y)

#Define a ndarray, having equally spaced 30 numbers between 10 and 20.
y1 = np.linspace(10, 20, 30) 
print(y1)

[ 3.  7. 11. 15.]
[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


### Random Numbers Generator
#### rand, randint

In [41]:
np.random.seed(100) # setting seed
x = np.random.rand(3) # 3 random numbers between 0 and 1

print(x)

[0.54340494 0.27836939 0.42451759]


In [50]:
np.random.seed(100) # setting seed
y = np.random.randint(10, 50, 3) # 3 random integers between 10 and 50

print(y)

[18 34 13]


In [60]:
y = np.random.RandomState(100) # 3 random integers between 10 and 50
print(y)

### Simulating Normal Distribution

In [61]:
np.random.seed(100)
x = np.random.randn(3) # Standard normal distribution
print(x)

[-1.74976547  0.3426804   1.1530358 ]


In [42]:
np.random.seed(100)
x = 10 + 2*np.random.randn(3) # normal distribution with mean 10 and sd 2
print(x, end='\n\n')

#Simulate a random normal distribution of 20 elements, whose mean is 5 and standard deviation 2.5 . Capture the result in x5.
x1 = 5 + 2.5*np.random.randn(20)
print(x1)

[ 6.50046905 10.68536081 12.30607161]

[4.36890991 7.45330197 6.2855471  5.55294917 2.32489167 4.52626042
 5.63750361 3.85493254 6.08790872 3.54101237 7.04211768 6.68180201
 4.73897214 3.67179906 7.57433171 3.90466094 2.20420438 9.04745415
 8.85401294 4.37030215]


### Reading Data from a file

In [45]:
from io import StringIO
import numpy as np

x = StringIO('''88.25 93.45 72.60 90.90 72.3 78.85 92.15 65.75 90.5 92.45 89.25 94.50 88.70''')

d = np.loadtxt(x,delimiter=' ')

print(d)

print(d.ndim, d.shape)

[88.25 93.45 72.6  90.9  72.3  78.85 92.15 65.75 90.5  92.45 89.25 94.5
 88.7 ]
1 (13,)


# 2. Array Shape Manipulation

### Reshaping ndarrays

In [49]:
np.random.seed(100)
x = np.random.randint(10, 100, 8)
print(x, end='\n\n')

y = x.reshape(2,4)
print(y, end='\n\n')

z = x.reshape(2,2,2)
print(z)

[18 34 77 97 89 58 20 62]

[[18 34 77 97]
 [89 58 20 62]]

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]]


### Stacking arrays - vertically & horizontally

In [50]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [51]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

### Splitting Arrays - Vertically and Horizontally

In [62]:
# vsplit
x = np.arange(30).reshape(6, 5)
res = np.vsplit(x, 3) # number of arrays to be created - 3
print(x, end='\n\n')
print(res, end='\n\n')
print(res[0], end='\n\n')
print(res[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [59]:
# It is also possible to split at specific row numbers using vsplit
x = np.arange(30).reshape(6, 5)

res = np.vsplit(x, (2, 5)) #first split on index 2 (row 3) and then on 5th index (row6)

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]


In [65]:
# hsplit
x = np.arange(10).reshape(2, 5)
res = np.hsplit(x, (2,4))

print(x, end='\n\n')
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


# 3. Basic Operations on Numpy Arrays

### Scalars

In [78]:
x = np.arange(6).reshape(2,3)

print(x + 10, end='\n\n')
print(x * 3, end='\n\n')
print(x % 2)

[[10 11 12]
 [13 14 15]]

[[ 0  3  6]
 [ 9 12 15]]

[[0 1 0]
 [1 0 1]]


In [79]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])

print(x + y, end='\n\n')
print(x * y)

[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]


### NumPy Array Methods

In [2]:
import numpy as np

x = np.array([[0,1], [2,3]])

print(np.square(x), end='\n\n')

print(np.sin(x))

[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]


In [4]:
x = np.array([[0,1], [2, 3]])

print(x.sum(), end='\n\n')

print(x.sum(axis=0), end='\n\n')

print(x.sum(axis=1))

6

[2 4]

[1 5]


# 4. SLICING

#### A slice object is of the form start:end:step. All three are optional.
#### Having only a single number inside square brackets refer to start index.

In [9]:
x = np.array([5, 10, 15, 20, 25, 30, 35])

print(x[1])  # Indexing

print(x[1:6]) # Slicing

print(x[1:6:3]) # Slicing

10
[10 15 20 25 30]
[10 25]


In [7]:
import numpy as np
y = np.array([[0, 1, 2], [3, 4, 5]])

print(y[0:2, 1:2]) 

print(y[1])   

print(y[:, 1]) 

[[1]
 [4]]
[3 4 5]
[1 4]


In [14]:
x = np.array([[-1, 1], [-2, 2]])

for row in x:
    print('Row :',row)
  
for a in np.nditer(x):
    print(a)

Row : [-1  1]
Row : [-2  2]
-1
1
-2
2


#### Boolean Indexing

In [15]:
x = np.arange(10).reshape(2,5)

condition = x % 2 == 0

print(condition)
print(x[condition])

[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [36]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
