## 1. Autoregression

In [2]:
import pandas as pd
import numpy as np

In [3]:
sampleRng = pd.date_range(start='2017', periods=120, freq='MS')

sampleTs = pd.Series(np.random.randint(-10, 10, size=len(sampleRng)), sampleRng).cumsum()

In [4]:
sampleTs.head()

2017-01-01     8
2017-02-01     8
2017-03-01    11
2017-04-01    12
2017-05-01    13
Freq: MS, dtype: int32

Autoregressive Integrated Moving Average (**ARIMA**)
The parameter order = is very important in calling the right function for forecasting

p: The number of lag observations included in the model, also called the lag order<br>
d: The number of times that the raw observations are differenced, also called the degree of differencing.<br>
q: The size of the moving average window, also called the order of moving average

An ARIMA model can be created using the statsmodels library as follows:

Define the model by calling ARIMA() and passing in the p, d, and q parameters.<br>
The model is prepared on the training data by calling the fit() function.<br>
Predictions can be made by calling the **predict()** function and specifying the index of the time or times to be predicted.<br>
**forecast()** function, which performs a one-step forecast using the model.

In [6]:
from statsmodels.tsa.arima_model import ARIMA 

model = ARIMA(sampleTs, order=(1, 1, 0)) 

predValues = model.fit()

predValues.summary()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\signaltools.py:1341: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out_full[ind] += zi
C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\signaltools.py:1350: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an arra

<class 'statsmodels.iolib.summary.Summary'>
"""
                             ARIMA Model Results                              
==============================================================================
Dep. Variable:                    D.y   No. Observations:                  119
Model:                 ARIMA(1, 1, 0)   Log Likelihood                -382.897
Method:                       css-mle   S.D. of innovations              6.042
Date:                Mon, 20 May 2019   AIC                            771.794
Time:                        10:47:34   BIC                            780.132
Sample:                    02-01-2017   HQIC                           775.180
                         - 12-01-2026                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6174      0.526     -1.174      0.243      -1.648       0.413
ar.L1.D.y     -0.0537      0.092     -0.585      0.560      -0.234       0.126
                                    Roots                                    
=============================================================================
                  Real          Imaginary           Modulus         Frequency
-----------------------------------------------------------------------------
AR.1          -18.6048           +0.0000j           18.6048            0.5000
-----------------------------------------------------------------------------
"""

In [7]:
predValues.forecast()

(array([-66.08058524]),
 array([6.0416199]),
 array([[-77.92194265, -54.23922784]]))

In [8]:
predValues.predict()

2017-02-01   -0.617404
2017-03-01   -0.650589
2017-04-01   -0.811838
2017-05-01   -0.704339
2017-06-01   -0.704339
2017-07-01   -0.220593
2017-08-01   -0.650589
2017-09-01   -0.596840
2017-10-01   -0.650589
2017-11-01   -1.134335
2017-12-01   -0.220593
2018-01-01   -0.543090
2018-02-01   -1.080585
2018-03-01   -0.973086
2018-04-01   -1.080585
2018-05-01   -0.811838
2018-06-01   -1.134335
2018-07-01   -0.435591
2018-08-01   -0.274343
2018-09-01   -0.113094
2018-10-01   -0.435591
2018-11-01   -1.026836
2018-12-01   -0.166844
2019-01-01   -0.274343
2019-02-01   -0.166844
2019-03-01   -0.328092
2019-04-01   -1.134335
2019-05-01   -1.080585
2019-06-01   -0.274343
2019-07-01   -0.865587
                ...   
2024-07-01   -0.489341
2024-08-01   -0.328092
2024-09-01   -0.328092
2024-10-01   -0.543090
2024-11-01   -0.704339
2024-12-01   -0.811838
2025-01-01   -0.650589
2025-02-01   -0.113094
2025-03-01   -1.080585
2025-04-01   -0.220593
2025-05-01   -0.811838
2025-06-01   -0.919337
2025-07-01 

## Moving Average

In [10]:
model = ARIMA(sampleTs, order=(0, 1, 1)) 

movingAvgRes = model.fit()

movingAvgRes.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             ARIMA Model Results                              
==============================================================================
Dep. Variable:                    D.y   No. Observations:                  119
Model:                 ARIMA(0, 1, 1)   Log Likelihood                -382.895
Method:                       css-mle   S.D. of innovations              6.042
Date:                Mon, 20 May 2019   AIC                            771.790
Time:                        11:12:44   BIC                            780.127
Sample:                    02-01-2017   HQIC                           775.175
                         - 12-01-2026                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6175      0.524     -1.179      0.241      -1.644       0.409
ma.L1.D.y     -0.0546      0.093     -0.588      0.558      -0.237       0.127
                                    Roots                                    
=============================================================================
                  Real          Imaginary           Modulus         Frequency
-----------------------------------------------------------------------------
MA.1           18.3197           +0.0000j           18.3197            0.0000
-----------------------------------------------------------------------------
"""

In [11]:
movingAvgRes.forecast()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]


(array([-66.05973594]),
 array([6.04150608]),
 array([[-77.90087027, -54.21860161]]))